# -*- coding: utf-8 -*-
"""Correlation Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zq8N-F17UrWOB9EwPa0SdDfmnb64KeIw
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/Jahangirpuri.csv', parse_dates=[0])
df

"""# **Pearson Correlation**

###Correlation among Pollutants
"""

from scipy.stats import pearsonr

for i in df.columns.tolist()[1:]:
  for j in df.columns.tolist()[1:]:
    if i!=j:
      corr, _ = pearsonr(df[i],df[j])
      print('%s & %s: %.3f\n' % (i, j, corr), end='')

cormat = df.corr()
round(cormat,2)

sns.set(rc = {'figure.figsize':(10,8)})
plt.title('PM2.5 - Pearson Correlation of Stations')
sns.heatmap(cormat, annot=True)

pd.plotting.scatter_matrix(df, color='red', figsize=(15,10), hist_kwds={'color':['black']})
plt.show()

"""###Correlation with weather parameters"""

#comparing weather parameters

df2 = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/Jahangirpuri_weather.csv', parse_dates=[0])

df['AT'] = df2['AT']
df['RH'] = df2['RH']
df['WS'] = df2['WS']

df

cormat = df.corr()
round(cormat,2)

sns.set(rc = {'figure.figsize':(10,8)})
plt.title('PM2.5 - Pearson Correlation of Stations')
sns.heatmap(cormat, annot=True)

"""###Correlation among Stations"""

pm25_df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/PM2.5/2019.csv', parse_dates=[0])
pm25_df.head()

pm10_df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/PM10/2019.csv', parse_dates=[0])
no2_df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/NO2/2019.csv', parse_dates=[0])
co_df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/CO/2019.csv', parse_dates=[0])
ozone_df = pd.read_csv('/content/gdrive/MyDrive/Covid Pollutants Analysis/Ozone/2019.csv', parse_dates=[0])

cormat = pm25_df.corr()
round(cormat,2)

sns.set(rc = {'figure.figsize':(10,8)})
plt.title('PM2.5', size=20)
sns.heatmap(cormat, cmap='Reds')

cormat = pm10_df.corr()
round(cormat,2)
sns.set(rc = {'figure.figsize':(10,8)})
plt.title('PM10', size=20)
sns.heatmap(cormat, cmap='Reds')

cormat = no2_df.corr()
round(cormat,2)
sns.set(rc = {'figure.figsize':(10,8)})
plt.title('NO2', size=20)
sns.heatmap(cormat, cmap='Blues')

cormat = co_df.corr()
round(cormat,2)
sns.set(rc = {'figure.figsize':(10,8)})
plt.title('CO', size=20)
sns.heatmap(cormat, cmap='Blues')

cormat = ozone_df.corr()
round(cormat,2)
sns.set(rc = {'figure.figsize':(10,8)})
plt.title('Ozone', size=20)
sns.heatmap(cormat, cmap='Blues')